### ISSUE TITLE
微软拼音的词库不可用，其他的未测试

### ISSUE THREAD

**Issue by Scighost** [xunkong/GenshinWords#1]
拉取了 [studyzy/imewlconverter](https://github.com/studyzy/imewlconverter) 的最新代码，无论是 CMD 还是 GUI，转换为微软拼音词库后，都会导入失败（文件格式错误或文件已损坏）。但是使用 [v2.9.0](https://github.com/studyzy/imewlconverter/releases/tag/v2.9.0)（2020年1月发布） 转换后却能导入成功。原因未知。

**Comment by anlanp** [comment]
感谢作者！
今天添加微软词库成功了。添加的是3.4.1ver里的Win10微软拼音词库.dat。通过微软拼音输入法---词库和自学习--用户自定义短语--导入、导出或清除用户自定义短语--导入-Win10微软拼音词库.dat 成功的。

另外请问作者会更新枫丹版本吗~

**Comment by Scighost** [comment]
@anlanp 4.3版本的词库已发布
